### PR TITLE
Invoice Feature

### LINKED ISSUE #27: [5-02] As the system, I want to automatically generate and send invoices once a membership is approved
# As the system, I want to automatically generate and send invoices once a membership is approved

Estimation: 6 hours

### PR DESCRIPTION
**Pull request by westerandr**
# Invoice Feature

## Description

#27

## Motivation and Context

This closes #27

Upon member acceptance by an admin or coordinator. An invoice will be generated for the user, they will be notified via email of the invoice. The CTA button on the email will link to the invoice pdf where the user can view and download the invoice.

## How has this been tested?

Automated Tests.

Run `composer install` to install new package.

## Screenshots (if appropriate)
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code fulfills the acceptance criteria.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ainsofs** [comment]
> Hi @westerandr , js had a chance to hv a look. Malo looks good so far. Some comments:
> 
>     1. The document that is generated is public. Meaning anyone with the link can access the invoice . Better to make it private and only accessible to user, exec and coordinator roles.
> 
>     2. If you lose the email there is no way easy way to access the invoice. Be good to have a link to it somewhere. Maybe an invoice section for the signup application.
> 
>     3. The details on the invoice are from the home tab. Probably best to use the work details tab. We could have another ticket for the applicant to choose which details to be used for invoice (home or work)
> 
>     4. The dollar sign after the number looks a bit weird. Maybe have the $ then the number in the invoice
> 
> 
> How do we update the Invoice address and details?

I have addressed all the concerns here

**Comment by ainsofs** [comment]
Pls review, if ok squash commit @westerandr

**Review by ainsofs — DISMISSED** [review]
Made changes

**Comment by westerandr** [comment]
Malo @ainsofs looks good! Just some conflicts that need to be fixed before it can be squashed and merged into main.

**Pull request merged**
